### ISSUE TITLE
WS4PY contains a package that CherryPy deprecates in >=9.0.0

### ISSUE THREAD

**Issue by migetman9** [magfest/sideboard#56]
WS4PY has `import cherrypy.wsgiserver` which has apparently been removed and replaced with cheroot, until further notice. I do not know a fix. I am currently using CherryPy 8.9.1. Thought I'd log the issue for future reference though

**Comment by EliAndrewC** [comment]
Good to know, thanks!  I'll probably just make a PR into ws4py to fix this.

**Comment by binary1230** [comment]
just saw this on latest deploy with our puppet config as well

**Comment by binary1230** [comment]
our version of cherrypy that recent deploys are trying to use is: CherryPy-10.1.0

**Comment by binary1230** [comment]
it looks like someone has already submitted a PR for this:
https://github.com/Lawouach/WebSocket-for-Python/pull/206

**Comment by binary1230** [comment]
ok, I could call this done since we now have https://github.com/magfest/sideboard/commit/698dcfd10641a243541fc4d482538dd8a02c2100 merged in.

BTW, realized, the reason we are seeing this suddenly is because in https://github.com/magfest/sideboard/pull/27, we updated sideboard with a bunch of upstream changes changed the requirements.txt of sideboard from:
```cherrypy==3.6.0```
to 
```cherrypy>=3.6.0```

That's all solid, but then cherrypy's latest versions (as of Jan 7) refactored their internal 'wsgiserver' implementation into a new project called cheroot.  That's also fine.  But, another package we use, ws4py, still is referencing the old wsgiserver package and needs to be updated to use cheroot.  So until that is fixed upstream in ws4py (a PR is already open: https://github.com/Lawouach/WebSocket-for-Python/pull/206), we need to pin cherrypy at an older version.

**Comment by binary1230** [comment]
so let's call this issue able to be closed when: ws4py updates their code to be compatible with cherrypy >= 9.0

**Comment by binary1230** [comment]
just a quick update, the upstream PR was closed, so it should be safe to change our requirements.txt to allow deployment of the current version of cherrypy.
